runtime: nodejs20
env: standard

# Environment variables will be set via Google Cloud Console
# or you can add them here if needed

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10

handlers:
  - url: /.*
    script: auto
    secure: always 